apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- envs:
  - backend-config.env
  name: train-config

generatorOptions:
  disableNameSuffixHash: true
images:
- name: team-train-dev-backend
  newName: 889951087651.dkr.ecr.ap-northeast-2.amazonaws.com/team-train-dev-backend
  newTag: f02d91270f7d7bb3c8fc38358dbc5964a8df06fd
