apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- envs:
  - backend-config.env
  name: train-config

generatorOptions:
  disableNameSuffixHash: true

images:
- name: team-train-dev-backend
  newName: 009152047332.dkr.ecr.ap-northeast-2.amazonaws.com/team-train-prod-backend
  newTag: a1ca031f0fc30ee776da2ea11040d55aa41b60ca

patchesStrategicMerge:
- targetgroupbinding-patch.yaml
