apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- envs:
  - backend-config.env
  name: train-config

generatorOptions:
  disableNameSuffixHash: true

images:
- name: team-train-dev-backend
  newName: 009152047332.dkr.ecr.ap-northeast-2.amazonaws.com/team-train-prod-backend
  newTag: 85048f7b2c96819fc40c90a244b7739602cfd1a9

patchesStrategicMerge:
- targetgroupbinding-patch.yaml
