apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- envs:
  - backend-config.env
  name: train-config

generatorOptions:
  disableNameSuffixHash: true

images:
- name: team-train-dev-backend
  newName: 009152047332.dkr.ecr.ap-northeast-2.amazonaws.com/team-train-prod-backend
  newTag: 18829cd4f724e898e2c29eabd1ba7259f1b443c2

patchesStrategicMerge:
- targetgroupbinding-patch.yaml
