# 이 파일은 Terraform에 의해 자동 생성되었습니다. 직접 수정하지 마세요.
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: backend-targetgroup-binding
  namespace: default
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:009152047332:targetgroup/team-train-prod-app-tg/fccca319da616fb1
