apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: train-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 80       
      targetPort: 80 # Nginx 기본 포트에 맞춰 80으로 변경
      protocol: TCP
  selector:
    app: train-backend  
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: backend-targetgroup-binding
  namespace: default
spec:
  # EKS 1단계 배포 완료 후 출력되는 실제 target group ARN으로 아래 값을 교체해야 합니다.
  targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:009152047332:targetgroup/team-train-dev-app-tg/a1916835a0e02a1c"
  
  serviceRef:
    name: backend-service
    port: 80              