apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend-app
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 80       
      targetPort: 8080 
      protocol: TCP
  selector:
    app: backend-app  
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: backend-targetgroup-binding
  namespace: default
spec:
  # 타겟 그룹의 ARN
  targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:889951087651:targetgroup/team-train-dev-app-tg/c00e067558a34418" 
  
  serviceRef:
    name: backend-service
    port: 80              