# 뒷부분 DB 적재 Worker (3~5대 고정)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-db-worker
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-worker
  template:
    metadata:
      labels:
        app: train-worker
    spec:
      serviceAccountName: booking-sa 
      containers:
      - name: worker-container
        image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/train-worker:latest
        envFrom:
        - configMapRef:
            name: train-config
        - secretRef:
            name: train-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"