apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: booking-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: train-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: train-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: team-train-db-credentials
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: team-train-db-credentials
        property: DB_PASSWORD